# -*- coding: utf-8 -*-
"""1DCNN.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T3IhnNbkpYvaEPa3KX9UzvgNy-JbBpJd
"""

import os
import numpy as np
import pandas as pd
import kagglehub
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow import keras
from tensorflow.keras import layers

keras.utils.set_random_seed(42)

# ---------- 1. Load ----------
path = kagglehub.dataset_download("hassan06/nslkdd")
cols = ["duration","protocol_type","service","flag","src_bytes","dst_bytes","land",
"wrong_fragment","urgent","hot","num_failed_logins","logged_in","num_compromised",
"root_shell","su_attempted","num_root","num_file_creations","num_shells",
"num_access_files","num_outbound_cmds","is_host_login","is_guest_login","count",
"srv_count","serror_rate","srv_serror_rate","rerror_rate","srv_rerror_rate",
"same_srv_rate","diff_srv_rate","srv_diff_host_rate","dst_host_count",
"dst_host_srv_count","dst_host_same_srv_rate","dst_host_diff_srv_rate",
"dst_host_same_src_port_rate","dst_host_srv_diff_host_rate","dst_host_serror_rate",
"dst_host_srv_serror_rate","dst_host_rerror_rate","dst_host_srv_rerror_rate",
"label","difficulty"]

train = pd.read_csv(os.path.join(path, "KDDTrain+.txt"), names=cols)
test  = pd.read_csv(os.path.join(path, "KDDTest+.txt"),  names=cols)
df = pd.concat([train, test], ignore_index=True).drop(columns="difficulty")
print("combined:", df.shape)

# ---------- 2. Labels + encoding ----------
y = (df.pop("label") != "normal").astype(int).values
X = pd.get_dummies(df, columns=["protocol_type", "service", "flag"]).astype("float32").values
feature_names = pd.get_dummies(df, columns=["protocol_type", "service", "flag"]).columns.tolist()

# ---------- 3. Split 60 / 15 / 25 (stratified) ----------
X_tmp, X_test, y_tmp, y_test = train_test_split(
    X, y, test_size=0.25, stratify=y, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(
    X_tmp, y_tmp, test_size=0.20, stratify=y_tmp, random_state=42)  # 0.15 / 0.75 = 0.20

scaler = MinMaxScaler().fit(X_train)             # fit on train only
X_train, X_val, X_test = [scaler.transform(a)[..., None] for a in (X_train, X_val, X_test)]
print("train/val/test:", len(X_train), len(X_val), len(X_test))

# ---------- 4. 1D CNN ----------
model = keras.Sequential([
    layers.Input(shape=X_train.shape[1:]),
    layers.Conv1D(64, 3, padding="same", activation="relu"),
    layers.BatchNormalization(),
    layers.MaxPooling1D(2),
    layers.Conv1D(128, 3, padding="same", activation="relu"),
    layers.BatchNormalization(),
    layers.MaxPooling1D(2),
    layers.Conv1D(128, 3, padding="same", activation="relu"),
    layers.GlobalMaxPooling1D(),
    layers.Dense(64, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(1, activation="sigmoid"),
])
model.compile(optimizer=keras.optimizers.Adam(learning_rate=1e-3, weight_decay=1e-4),
              loss="binary_crossentropy", metrics=["accuracy"])
model.summary()

# ---------- 5. Train (fixed 20 epochs, no early stopping) ----------
history = model.fit(X_train, y_train, validation_data=(X_val, y_val),
                    epochs=20, batch_size=256, verbose=2)

# ---------- 6. Evaluate ----------
pred = (model.predict(X_test, verbose=0) > 0.5).astype(int).ravel()
print(classification_report(y_test, pred, target_names=["normal", "attack"], digits=4))
print("confusion matrix:\n", confusion_matrix(y_test, pred))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

os.makedirs("results/1d_cnn", exist_ok=True)
tag = "nsl"   # use "unsw" for UNSW-NB15

# metrics
row = pd.DataFrame([{
    "dataset": tag, "model": "1d_cnn",
    "accuracy": accuracy_score(y_test, pred),
    "precision": precision_score(y_test, pred),
    "recall": recall_score(y_test, pred),
    "f1": f1_score(y_test, pred),
}])
mpath = "results/1d_cnn/metrics.csv"
row.to_csv(mpath, mode="a", header=not os.path.exists(mpath), index=False)

# confusion matrix
cm = confusion_matrix(y_test, pred)
fig, ax = plt.subplots(figsize=(4, 4))
ax.imshow(cm, cmap="Blues")
ax.set_xticks([0, 1], ["normal", "attack"]); ax.set_yticks([0, 1], ["normal", "attack"])
ax.set_xlabel("Predicted"); ax.set_ylabel("True")
for i in range(2):
    for j in range(2):
        ax.text(j, i, cm[i, j], ha="center", va="center",
                color="white" if cm[i, j] > cm.max() / 2 else "black")
fig.tight_layout(); fig.savefig(f"results/1d_cnn/confusion_matrix_{tag}.png", dpi=150)

# training curves
fig, axs = plt.subplots(1, 2, figsize=(9, 3.5))
axs[0].plot(history.history["loss"], label="train"); axs[0].plot(history.history["val_loss"], label="val")
axs[0].set_title("Loss"); axs[0].set_xlabel("Epoch"); axs[0].legend()
axs[1].plot(history.history["accuracy"], label="train"); axs[1].plot(history.history["val_accuracy"], label="val")
axs[1].set_title("Accuracy"); axs[1].set_xlabel("Epoch"); axs[1].legend()
fig.tight_layout(); fig.savefig(f"results/1d_cnn/training_curves_{tag}.png", dpi=150)

import os
import shap
import lime
import lime.lime_tabular
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

os.makedirs("results/1d_cnn", exist_ok=True)

# ---------- Feature names ----------
# must match the exact columns used to build X (same order, before .values)
feature_names = pd.get_dummies(df, columns=["protocol_type", "service", "flag"]).columns.tolist()

# ---------- SHAP ----------
np.random.seed(42)
background = X_train[np.random.choice(len(X_train), 100, replace=False)]
explainer = shap.GradientExplainer(model, background)

sample_idx = np.random.choice(len(X_test), 200, replace=False)
X_sample = X_test[sample_idx]
y_sample = y_test[sample_idx]

shap_values = explainer.shap_values(X_sample)
sv = np.array(shap_values).squeeze()      # (200, n_features)
X_flat = X_sample.squeeze(-1)             # (200, n_features)

# global explanation
shap.summary_plot(sv, X_flat, feature_names=feature_names, show=False)
plt.tight_layout()
plt.savefig("results/1d_cnn/shap_summary_nsl.png", dpi=150, bbox_inches="tight")
plt.close()

# baseline for force plot (GradientExplainer has no expected_value)
baseline = float(model.predict(background, verbose=0).mean())

# ---------- Pick samples: one correct, one misclassified (if any) ----------
preds = (model.predict(X_sample, verbose=0).ravel() > 0.5).astype(int)
correct_idx = np.where(preds == y_sample)[0]
wrong_idx = np.where(preds != y_sample)[0]

picks = [("correct", correct_idx[0])]
if len(wrong_idx) > 0:
    picks.append(("misclassified", wrong_idx[0]))

for tag, i in picks:
    print(f"[{tag}] sample {i} — predicted: {preds[i]}, true: {y_sample[i]}, "
          f"predicted prob: {model.predict(X_sample[i:i+1], verbose=0)[0][0]:.4f}")

    shap.force_plot(baseline, sv[i], X_flat[i],
                     feature_names=feature_names, matplotlib=True, show=False)
    plt.tight_layout()
    plt.savefig(f"results/1d_cnn/shap_force_{tag}_nsl.png", dpi=150, bbox_inches="tight")
    plt.close()

# ---------- LIME ----------
X_train_flat = X_train.squeeze(-1)

def predict_fn(x):
    x = x[..., None]
    prob = model.predict(x, verbose=0).ravel()
    return np.column_stack([1 - prob, prob])

lime_explainer = lime.lime_tabular.LimeTabularExplainer(
    X_train_flat, feature_names=feature_names,
    class_names=["normal", "attack"], mode="classification")

for tag, i in picks:
    exp = lime_explainer.explain_instance(X_flat[i], predict_fn, num_features=10)
    exp.save_to_file(f"results/1d_cnn/lime_{tag}_nsl.html")
    print(f"[{tag}] LIME:", exp.as_list())

from google.colab import files
for f in ["shap_summary_nsl.png", "shap_force_correct_nsl.png",
          "shap_force_misclassified_nsl.png", "lime_correct_nsl.html",
          "lime_misclassified_nsl.html"]:
    files.download(f"results/1d_cnn/{f}")